要求仕様書、クラス図
a191409/System_design pull request #1
Opened 2021-06-22 15:20 UTC by a191409

要求仕様書に関してはある程度まとまっていて完成しましたが、クラス図はあまりまとまりきっていないです。お手隙の際によろしくお願いいたします。

2021-06-23 11:28 UTC, a171413 requested changes
全体的に〇〇機能と言うからにはインプットとアウトプットが具体的に述べられている必要がある。そこら辺が不足しているので書き足してください。
あとは細かい例外系列を考えたほうがいいかもしれない

2021-06-23 11:28 UTC, a171413 commented on docs/System_/Requisition_sheet.md
> +
機能の話に入る前にシステムの概要について述べられていると良いね

2021-06-23 11:28 UTC, a171413 commented on docs/System_/Requisition_sheet.md
> +|**基本系列**|1. システムは対戦結果入力画面を表示する。<br>2.アクターは対戦結果を入力する。<br>3.システムは入力されたデータに不足がないか、及びエラーのないデータか否かチェックする。<br>4.システムは登録後の画面を表示する。|
「入力する」というだけではどう入力するかが不明瞭
入力するものを詳しく書いたほうがいい。そうでないとエラーのないデータとかって話がわからない。

2021-06-23 11:28 UTC, a171413 commented on docs/System_/Requisition_sheet.md
> +|**基本系列**|1. システムは対戦結果検索画面を表示する。<br>2.アクターは対戦検索したい条件を入力する。<br>3.システムは入力されたデータから、条件を満たす対戦結果を検索する。。<br>4.システムは検索で見つかった対戦結果を表示する。|
検索する条件には何があるのかわからない。

2021-06-23 11:28 UTC, a171413 commented on docs/System_/Requisition_sheet.md
> +|**例外系列**|a.3で入力データが不足がある場合<br>　a1.システムはエラーメッセージを表示する。<br>　a2.基本系列1に戻る。<br>b.3で対戦結果の試合日が未来を指している場合<br>　b1.システムはエラーメッセージを表示する。<br>　b2.基本系列1に戻る。|
これはAさんとBさんが対戦した時、AさんもBさんも同じ結果を入力することになるのかな？
これを許さないのであれば例外系列に書き足したほうがよさそう

2021-06-25 16:13 UTC, a191409 commented
レビューありがとうございました。
レビューを踏まえて、改めて要求仕様書を追記いたしました。
GitHubの使い方になれず、想定外のファイルが追加されてしまったので怒涛に削除してある状況です。
よろしくお願いいたします。

2021-07-02 16:15 UTC, a171413 reviewed
クラス図はかなり考え直す必要がありそう
仕様書はいい感じになってきたけど，ユーザーをアクターと呼ぶ必要はない気がする
アクターというのはシステムに作用するもの全てを言うけど，今回はユーザーのみなので．

2021-07-02 16:15 UTC, a171413 commented on docs/Class.puml
> +}
Opponentというのは「相手」という認識でいいかな？
だとすると相手を認識する自分という存在も必要だと思うのだけど，それが抜けている気がする

2021-07-02 16:15 UTC, a171413 commented on docs/Class.puml
> +    int Opponent_id
Opponentクラスに対するコメントと通ずるところがあるんだけど，ResultにOpponent_idを1つだけ持つとなると，ユーザーは1人しか使えない
例えばユーザーが3人（id1のAさん，id2のBさん，id3のCさんとする）いたとする．
Resultに
{
　id:1,
　round: 1,
　didwin: true,
　Opponent_id: 1,
　Match_id: 2
}
があってもAさんに勝ったという情報だけで，誰が勝ったかはわからない．
この辺はもし時間が合えば研究室で練り直しましょう．

2021-07-02 16:15 UTC, a171413 commented on docs/Class.puml
> +Match "0..*" -- "0..*" Result
Resultから見てOpponentやMatchは0以上なんだろうか

2021-07-02 16:15 UTC, a171413 commented on docs/Requisition_sheet.md
> +|**例外系列**|a.3で対戦結果が見つからない場合<br>　a1.システムはエラーメッセージを表示する。<br>　a2.基本系列1に戻る。<br>b.3で入力された対戦結果の試合日が未来を指している場合<br>　b1.システムはエラーメッセージを表示する。<br>　b2.基本系列1に戻る。|
対戦結果が見つからない時，エラーを表示するでもいいけど，単に何も表示しないでもいいんじゃないかと思った
（エラーの表示を設定するのは面倒なので）

2021-07-07 03:12 UTC, merged